resolver: lts-13.0

packages:
- .

extra-deps:
- symbols-0.3.0.0 
- typed-encoding-0.2.1.0  
- containers-0.5.11.0
- regex-compat-0.93.1
- HaXml-1.25.5
- encoding-0.8.5 
# - git: git@github.com:dmwit/encoding
#   commit: 0.8.3

